# Generated by Django 4.1.5 on 2023-01-20 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appeal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('date_created', models.DateTimeField(auto_created=True)),
                ('fk_admin', models.IntegerField()),
                ('appeal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appeal.appeal')),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
