version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db_postgres

  db_postgres:
    image: postgres:15-alpine3.17
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=estudent
      - POSTGRES_DB=estudent_dev
      - POSTGRES_PASSWORD=estudent


volumes:
  postgresql_data:
