# Generated by Django 4.1.5 on 2023-01-20 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discipline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('etcs', models.IntegerField()),
                ('fk_discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discipline.discipline')),
            ],
        ),
    ]
