# Generated by Django 4.1.5 on 2023-01-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='etcs',
            new_name='ects',
        ),
    ]
