# Generated by Django 4.1.5 on 2023-01-22 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appeal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='fk_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
